//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trawell_FINAL1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int id { get; set; }
        public string jobs { get; set; }
        public string texts { get; set; }
        public string photos { get; set; }
        public string names { get; set; }
    }
}
