//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trawell_FINAL1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.Activity_ActivityItems = new HashSet<Activity_ActivityItems>();
            this.Activity_Attract = new HashSet<Activity_Attract>();
            this.Activity_Nightlife = new HashSet<Activity_Nightlife>();
            this.Activity_photo = new HashSet<Activity_photo>();
        }
    
        public int id { get; set; }
        public string activ_name { get; set; }
        public string activ_location { get; set; }
        public string owner_email { get; set; }
        public int owner_number { get; set; }
        public string owner_site { get; set; }
        public string activ_descrption { get; set; }
        public string activ_description_heading { get; set; }
        public string activ_price { get; set; }
        public string activ_map { get; set; }
        public string activ_rewies { get; set; }
        public string activ_offers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_ActivityItems> Activity_ActivityItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Attract> Activity_Attract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Nightlife> Activity_Nightlife { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_photo> Activity_photo { get; set; }
    }
}
