//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trawell_FINAL1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_DefEquip
    {
        public int id { get; set; }
        public int def_equip_id { get; set; }
        public int cars_id { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Default_Equipment Default_Equipment { get; set; }
    }
}
