//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trawell_FINAL1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent_Suit
    {
        public int id { get; set; }
        public int rent_id { get; set; }
        public int suit_id { get; set; }
    
        public virtual Rental Rental { get; set; }
        public virtual Suitability Suitability { get; set; }
    }
}
