//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trawell_FINAL1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rental()
        {
            this.Bedrooms = new HashSet<Bedroom>();
            this.Rent_Ament = new HashSet<Rent_Ament>();
            this.Rent_Suit = new HashSet<Rent_Suit>();
            this.Rental_Photo = new HashSet<Rental_Photo>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string locations { get; set; }
        public string map { get; set; }
        public string descriptions { get; set; }
        public int price { get; set; }
        public int owner_number { get; set; }
        public string owner_email { get; set; }
        public string owner_site { get; set; }
        public int rental_male_num { get; set; }
        public int rental_shower_num { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bedroom> Bedrooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent_Ament> Rent_Ament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent_Suit> Rent_Suit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental_Photo> Rental_Photo { get; set; }
    }
}
