//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trawell_FINAL1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Trawell_DbaseEntities1 : DbContext
    {
        public Trawell_DbaseEntities1()
            : base("name=Trawell_DbaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Activity_ActivityItems> Activity_ActivityItems { get; set; }
        public virtual DbSet<Activity_Attract> Activity_Attract { get; set; }
        public virtual DbSet<Activity_items> Activity_items { get; set; }
        public virtual DbSet<Activity_Nightlife> Activity_Nightlife { get; set; }
        public virtual DbSet<Activity_photo> Activity_photo { get; set; }
        public virtual DbSet<Admin_Info> Admin_Info { get; set; }
        public virtual DbSet<Amenty> Amenties { get; set; }
        public virtual DbSet<Attraction> Attractions { get; set; }
        public virtual DbSet<Bedroom> Bedrooms { get; set; }
        public virtual DbSet<Car_pickup_Option> Car_pickup_Option { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Cars_Equip> Cars_Equip { get; set; }
        public virtual DbSet<Cars_Feat> Cars_Feat { get; set; }
        public virtual DbSet<Cars_group> Cars_group { get; set; }
        public virtual DbSet<Cars_PIckupFeat> Cars_PIckupFeat { get; set; }
        public virtual DbSet<Cars_trans> Cars_trans { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Default_Equipment> Default_Equipment { get; set; }
        public virtual DbSet<Engine> Engines { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<Nightlife> Nightlives { get; set; }
        public virtual DbSet<PickUp_Features> PickUp_Features { get; set; }
        public virtual DbSet<Rent_Ament> Rent_Ament { get; set; }
        public virtual DbSet<Rent_Suit> Rent_Suit { get; set; }
        public virtual DbSet<Rental_Photo> Rental_Photo { get; set; }
        public virtual DbSet<Rental> Rentals { get; set; }
        public virtual DbSet<Site_settings> Site_settings { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Slogan> Slogans { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<Suitability> Suitabilities { get; set; }
        public virtual DbSet<Cars_DefEquip> Cars_DefEquip { get; set; }
    }
}
